version: "3"

services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  elasticsearch:
    build:
      context: "docker_image/elasticsearch/."
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - 9200:9200
  app:
    build: .
    environment:
      DB_SERVERNAME: "db"
      ELASTICSEARCH_HOST: "elasticsearch"
    volumes:
      - .:/withMyChild
    working_dir: "/withMyChild"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server"
    links:
      - db
      - elasticsearch
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  data:
    driver: local
