version: "3"

services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  elasticsearch:
    build:
      context: docker_image/elasticsearch
    container_name: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
  app:
    build: .
    environment:
      DB_SERVERNAME: "db"
      ELASTICSEARCH_HOST: "elasticsearch"
    volumes:
      - .:/withmychild
    working_dir: "/withmychild"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.development"
    links:
      - db
      - elasticsearch
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
volumes:
  data:
    driver: local
