version: 2
jobs:
  build:
    working_directory: ~/withmychild
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          RAILS_ENV: 'test'
          RACK_ENV: 'test'
      - image: circleci/mysql:5.7.17
        environment:
           - MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
           - MYSQL_ROOT_HOST: '%'
           - MYSQL_ROOT_PASSWORD: ''
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
          - "http.host=0.0.0.0"
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ports:
          - 9200:9200
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          key: withMyChild-{{ checksum "Gemfile.lock" }}
      # bundler 2.0を使用
      - run: gem install bundler
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: withmychild-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake ridgepole:apply

      # Run rspec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run: bundle exec rubocop app
      - run: bundle exec rubocop spec

      - store_test_results:
          path: test_results
      - run: bash .circleci/setup-heroku.sh
      - deploy:
          name: heroku deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  heroku maintenance:on --app withmychild
                  git push heroku master
                  heroku run 'RAILS_ENV=production rake ridgepole:apply'
                  heroku maintenance:off --app withmychild
              fi
