version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/famipark
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: 'test'
          RACK_ENV: 'test'
      - image: circleci/mysql:5.7.17
        environment:
           - MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
           - MYSQL_ROOT_HOST: '%'
           - MYSQL_ROOT_PASSWORD: ''
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          key: famipark-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: famipark-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake ridgepole:apply

      # Run rspec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run: bundle exec rubocop app
      - run: bundle exec rubocop spec

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
