default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8mb4
  reconnect: false
  username: root
  password:
  strict: false
  pool: 5
  socket: <%= ENV['DAPHY_MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

development:
  <<: *default
  database: famipark_development
  host: localhost

photo_development:
  <<: *default
  database: famipark_photo_development
  host: localhost

test:
  <<: *default
  database: famipark_test
  host: localhost

photo_test:
  <<: *default
  database: famipark_photo_test
  host: localhost

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>

famiphoto_production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>

famipark_master_development:
  <<: *default
  database: famipark_development
  host: localhost

famipark_slave_development:
  <<: *default
  database: famipark_development
  host: localhost

famipark_master_test:
  <<: *default
  database: famipark_test
  host: localhost

famipark_slave_test:
  <<: *default
  database: famipark_test
  host: localhost

famipark_photo_master_development:
  <<: *default
  database: famipark_photo_development
  host: localhost

famipark_photo_slave_development:
  <<: *default
  database: famipark_photo_development
  host: localhost

famipark_photo_master_test:
  <<: *default
  database: famipark_photo_test
  host: localhost

famipark_photo_slave_test:
  <<: *default
  database: famipark_photo_test
  host: localhost

famipark_master_production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>

famipark_slave_production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>
