default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8mb4
  reconnect: false
  username: root
  password:
  strict: false
  pool: 5

development:
  <<: *default
  database: withmychild_development
  host: <%= ENV['DB_SERVERNAME'] %>

test:
  <<: *default
  database: withmychild_test
  host: <%= ENV['DB_SERVERNAME'] || '127.0.0.1' %>
  port: 3306

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>

