development:
  host:
    - '127.0.0.1'
  port:
    - 9200
  host:
    - '127.0.0.1'
  port:
    - 9200
test:
  host:
    - '127.0.0.1'
  port:
    - 9200
  host:
    - '127.0.0.1'
  port:
    - 9200
production:
  url:
    - <%= ENV['BONSAI_URL'] %>
  url:
    - <%= ENV['BONSAI_URL'] %>
