development:
  host:
    - <%= ENV['ELASTICSEARCH_HOST'] || '127.0.0.1' %>
  port:
    - 9200
test:
  host:
    - <%= ENV['ELASTICSEARCH_HOST'] || '127.0.0.1' %>
  port:
    - 9200
production:
  url:
    - <%= ENV['BONSAI_URL'] %>
